name: Check PR and notify

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Fastlane Build
        uses: maierj/fastlane-action@v2.0.1
        with:
            lane: 'app_assemble'

      - name: Notify to Telegrem
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          args: |
            ${{ github.event.pull_request.html_url }}

            Title   : ${{github.event.pull_request.title}}
            Author  : @${{github.actor}}
            Event   : ${{ github.event_name }}
